# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'EncryptoApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for EncryptoApp
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"  
  pod 'React', :path => '../node_modules/react-native'
  pod 'instabug-reactnative', :path => '../node_modules/instabug-reactnative'

  target 'EncryptoAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
source 'https://github.com/CocoaPods/Specs.git'
#platform :ios, '8.0'
#use_frameworks!

pod 'DCTAuth', :git => 'https://github.com/danielctull/DCTAuth.git'

pod 'SwiftyJSON', '4.0.0'      # 4.0.0
pod 'Charts', '3.1.1'          # 3.1.1
#pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'

post_install do |installer|
  installer.pods_project.targets.each do |target|
   target.build_configurations.each do |config|
   config.build_settings['SWIFT_VERSION'] = '4.0'
   end
  end
end