# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EncryptoApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EncryptoApp

  target 'EncryptoAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'DCTAuth', :git => 'https://github.com/danielctull/DCTAuth.git'

pod 'SwiftyJSON', '3.1.4'      # 4.0.0
pod 'Charts', '3.0.3'          # 3.1.1
